version: '3.8'
networks:
  kafka_network:
    driver: bridge
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - kafka_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka_network

  producer:
    build:
      context: .
      dockerfile: kafka-producer/Dockerfile
    platform: linux/arm64/v8
    depends_on:
      - kafka
    networks:
      - kafka_network

  consumer:
    build:
      context: .
      dockerfile: kafka-consumer/Dockerfile
    platform: linux/arm64/v8
    depends_on:
      - kafka
    networks:
      - kafka_network
